/*in this example, stored locally in folder "ESS" on the C: drive*/
LIBNAME ESS "C:\ESS";
/*To create formats (value labels): edit and run ESSformats program*/
%include "C:\ESS\ESS8e02_1_formats.sas";
run;
data x;
set ESS.ESS8e02_1;
* MS file;
FORMAT
        cntry $CNTRY.
       nwspol NWSPOL.
     netusoft NETUSOFT.
      netustm NETUSTM.
      ppltrst PPLTRST.
      pplfair PPLFAIR.
       pplhlp PPLHLP.
      polintr POLINTR.
     psppsgva PSPPSGVA.
     actrolga ACTROLGA.
     psppipla PSPPIPLA.
     cptppola CPTPPOLA.
      trstprl TRSTPRL.
      trstlgl TRSTLGL.
      trstplc TRSTPLC.
      trstplt TRSTPLT.
      trstprt TRSTPRT.
       trstep TRSTEP.
       trstun TRSTUN.
         vote VOTE.
     prtvtbat PRTVTBAT.
     prtvtcbe PRTVTCBE.
     prtvtfch PRTVTFCH.
     prtvtdcz PRTVTDCZ.
     prtvede1 PRTVEDE1F.
     prtvede2 PRTVEDE2F.
     prtvtfee PRTVTFEE.
     prtvtdes PRTVTDES.
     prtvtdfi PRTVTDFI.
     prtvtcfr PRTVTCFR.
     prtvtbgb PRTVTBGB.
     prtvtehu PRTVTEHU.
     prtvtbie PRTVTBIE.
     prtvtcil PRTVTCIL.
     prtvtbis PRTVTBIS.
     prtvtbit PRTVTBIT.
     prtvblt1 PRTVBLT1F.
     prtvblt2 PRTVBLT2F.
     prtvblt3 PRTVBLT3F.
     prtvtfnl PRTVTFNL.
     prtvtbno PRTVTBNO.
     prtvtdpl PRTVTDPL.
     prtvtcpt PRTVTCPT.
     prtvtdru PRTVTDRU.
     prtvtbse PRTVTBSE.
     prtvtesi PRTVTESI.
      contplt CONTPLT.
      wrkprty WRKPRTY.
       wrkorg WRKORG.
        badge BADGE.
      sgnptit SGNPTIT.
       pbldmn PBLDMN.
       bctprd BCTPRD.
     pstplonl PSTPLONL.
      clsprty CLSPRTY.
     prtclcat PRTCLCAT.
     prtclcbe PRTCLCBE.
     prtclfch PRTCLFCH.
     prtcldcz PRTCLDCZ.
     prtclede PRTCLEDE.
     prtclfee PRTCLFEE.
     prtclees PRTCLEES.
     prtcldfi PRTCLDFI.
     prtclefr PRTCLEFR.
     prtclbgb PRTCLBGB.
     prtclfhu PRTCLFHU.
     prtcldie PRTCLDIE.
     prtcldil PRTCLDIL.
     prtclbis PRTCLBIS.
     prtclcit PRTCLCIT.
     prtclblt PRTCLBLT.
     prtclenl PRTCLENL.
     prtclbno PRTCLBNO.
     prtclgpl PRTCLGPL.
     prtclept PRTCLEPT.
     prtcldru PRTCLDRU.
     prtclbse PRTCLBSE.
     prtclesi PRTCLESI.
      prtdgcl PRTDGCL.
      lrscale LRSCALE.
      stflife STFLIFE.
       stfeco STFECO.
       stfgov STFGOV.
       stfdem STFDEM.
       stfedu STFEDU.
      stfhlth STFHLTH.
      gincdif GINCDIF.
      mnrgtjb MNRGTJB.
      freehms FREEHMS.
     hmsfmlsh HMSFMLSH.
      hmsacld HMSACLD.
        euftf EUFTF.
      imsmetn IMSMETN.
      imdfetn IMDFETN.
      impcntr IMPCNTR.
      imbgeco IMBGECO.
      imueclt IMUECLT.
      imwbcnt IMWBCNT.
        happy HAPPY.
      sclmeet SCLMEET.
      inprdsc INPRDSC.
       sclact SCLACT.
       crmvct CRMVCT.
      aesfdrk AESFDRK.
       health HEALTH.
      hlthhmp HLTHHMP.
      atchctr ATCHCTR.
      atcherp ATCHERP.
       rlgblg RLGBLG.
       rlgdnm RLGDNM.
     rlgdnbat RLGDNBAT.
      rlgdnbe RLGDNBE.
     rlgdnach RLGDNACH.
     rlgdnade RLGDNADE.
     rlgdnafi RLGDNAFI.
      rlgdngb RLGDNGB.
      rlgdnhu RLGDNHU.
      rlgdnie RLGDNIE.
      rlgdnis RLGDNIS.
      rlgdnlt RLGDNLT.
      rlgdnnl RLGDNNL.
      rlgdnno RLGDNNO.
     rlgdnapl RLGDNAPL.
     rlgdnase RLGDNASE.
      rlgblge RLGBLGE.
      rlgdnme RLGDNME.
     rlgdebat RLGDEBAT.
      rlgdebe RLGDEBE.
     rlgdeach RLGDEACH.
     rlgdeade RLGDEADE.
     rlgdeafi RLGDEAFI.
      rlgdegb RLGDEGB.
      rlgdehu RLGDEHU.
      rlgdeie RLGDEIE.
      rlgdeis RLGDEIS.
      rlgdelt RLGDELT.
      rlgdenl RLGDENL.
      rlgdeno RLGDENO.
     rlgdeapl RLGDEAPL.
     rlgdease RLGDEASE.
       rlgdgr RLGDGR.
      rlgatnd RLGATND.
         pray PRAY.
      dscrgrp DSCRGRP.
      dscrrce DSCRRCE.
      dscrntn DSCRNTN.
      dscrrlg DSCRRLG.
      dscrlng DSCRLNG.
      dscretn DSCRETN.
      dscrage DSCRAGE.
      dscrgnd DSCRGND.
      dscrsex DSCRSEX.
      dscrdsb DSCRDSB.
      dscroth DSCROTH.
       dscrdk DSCRDK.
      dscrref DSCRREF.
      dscrnap DSCRNAP.
       dscrna DSCRNA.
      ctzcntr CTZCNTR.
     ctzshipc $CTZSHIPC.
      brncntr BRNCNTR.
     cntbrthc $CNTBRTHC.
     livecnta LIVECNTA.
      lnghom1 $LNGHOM1F.
      lnghom2 $LNGHOM2F.
      blgetmg BLGETMG.
       facntr FACNTR.
     fbrncntb $FBRNCNTB.
       mocntr MOCNTR.
     mbrncntb $MBRNCNTB.
      gvrfgap GVRFGAP.
      rfgfrpc RFGFRPC.
      rfgbfml RFGBFML.
      eneffap ENEFFAP.
       rdcenr RDCENR.
      cflsenr CFLSENR.
      elgcoal ELGCOAL.
      elgngas ELGNGAS.
      elghydr ELGHYDR.
       elgnuc ELGNUC.
       elgsun ELGSUN.
      elgwind ELGWIND.
       elgbio ELGBIO.
      wrpwrct WRPWRCT.
      wrenexp WRENEXP.
      wrdpimp WRDPIMP.
      wrdpfos WRDPFOS.
      wrntdis WRNTDIS.
      wrinspw WRINSPW.
       wrtcfl WRTCFL.
      wrtratc WRTRATC.
      clmchng CLMCHNG.
     clmthgt1 CLMTHGT1F.
     clmthgt2 CLMTHGT2F.
      ccnthum CCNTHUM.
      ccrdprs CCRDPRS.
      wrclmch WRCLMCH.
       ccgdbd CCGDBD.
      lkredcc LKREDCC.
      lklmten LKLMTEN.
      gvsrdcc GVSRDCC.
      ownrdcc OWNRDCC.
      inctxff INCTXFF.
      sbsrnen SBSRNEN.
      banhhap BANHHAP.
      dfincac DFINCAC.
      smdfslv SMDFSLV.
      uemplwk UEMPLWK.
      slvpens SLVPENS.
      slvuemp SLVUEMP.
      gvslvol GVSLVOL.
      gvslvue GVSLVUE.
      gvcldcr GVCLDCR.
      sbstrec SBSTREC.
      sbprvpv SBPRVPV.
      sbeqsoc SBEQSOC.
      sbbsntx SBBSNTX.
       sblazy SBLAZY.
      sblwcoa SBLWCOA.
      imsclbn IMSCLBN.
      uentrjb UENTRJB.
      lbenent LBENENT.
      bennent BENNENT.
        admub ADMUB.
        ubpay UBPAY.
        ubedu UBEDU.
        ubunp UBUNP.
      ub50pay UB50PAY.
      ub50edu UB50EDU.
      ub50unp UB50UNP.
      ub20pay UB20PAY.
      ub20edu UB20EDU.
      ub20unp UB20UNP.
      ubsppay UBSPPAY.
      ubspedu UBSPEDU.
      ubspunp UBSPUNP.
      bnlwinc BNLWINC.
      eduunmp EDUUNMP.
      wrkprbf WRKPRBF.
       basinc BASINC.
      eusclbf EUSCLBF.
      eudcnbf EUDCNBF.
       lkuemp LKUEMP.
      lknemny LKNEMNY.
     vteurmmb VTEURMMB.
     vteumbgb VTEUMBGB.
     vteubcmb VTEUBCMB.
        hhmmb HHMMB.
         gndr GNDR.
        gndr2 GNDR2F.
        gndr3 GNDR3F.
        gndr4 GNDR4F.
        gndr5 GNDR5F.
        gndr6 GNDR6F.
        gndr7 GNDR7F.
        gndr8 GNDR8F.
        gndr9 GNDR9F.
       gndr10 GNDR10F.
       gndr11 GNDR11F.
       gndr12 GNDR12F.
         agea AGEA.
        yrbrn YRBRN.
       yrbrn2 YRBRN2F.
       yrbrn3 YRBRN3F.
       yrbrn4 YRBRN4F.
       yrbrn5 YRBRN5F.
       yrbrn6 YRBRN6F.
       yrbrn7 YRBRN7F.
       yrbrn8 YRBRN8F.
       yrbrn9 YRBRN9F.
      yrbrn10 YRBRN10F.
      yrbrn11 YRBRN11F.
      yrbrn12 YRBRN12F.
      rshipa2 RSHIPA2F.
      rshipa3 RSHIPA3F.
      rshipa4 RSHIPA4F.
      rshipa5 RSHIPA5F.
      rshipa6 RSHIPA6F.
      rshipa7 RSHIPA7F.
      rshipa8 RSHIPA8F.
      rshipa9 RSHIPA9F.
     rshipa10 RSHIPA10F.
     rshipa11 RSHIPA11F.
     rshipa12 RSHIPA12F.
      icpart1 ICPART1F.
      rshpsts RSHPSTS.
      rshpsfi RSHPSFI.
      rshpsgb RSHPSGB.
     lvgptnea LVGPTNEA.
     dvrcdeva DVRCDEVA.
      icpart2 ICPART2F.
      iccohbt ICCOHBT.
       marsts MARSTS.
      marstfi MARSTFI.
      marstgb MARSTGB.
     maritalb MARITALB.
       chldhm CHLDHM.
      chldhhe CHLDHHE.
      domicil DOMICIL.
      edulvlb EDULVLB.
       eisced EISCED.
      edlveat EDLVEAT.
      edlvebe EDLVEBE.
      edlvdch EDLVDCH.
      edlvdcz EDLVDCZ.
      edubde1 EDUBDE1F.
      eduade2 EDUADE2F.
      eduade3 EDUADE3F.
      edlvdee EDLVDEE.
      edlvges EDLVGES.
      edlvdfi EDLVDFI.
      edlvdfr EDLVDFR.
      edubgb1 EDUBGB1F.
      eduagb2 EDUAGB2F.
      edagegb EDAGEGB.
      edlvdhu EDLVDHU.
      edlvdie EDLVDIE.
      edubil1 EDUBIL1F.
      eduail2 EDUAIL2F.
      edlvdis EDLVDIS.
      edlvdit EDLVDIT.
      edlvdlt EDLVDLT.
      edlvenl EDLVENL.
      edlvdno EDLVDNO.
      edlvepl EDLVEPL.
       edupl2 EDUPL2F.
      edlvdpt EDLVDPT.
      edlvdru EDLVDRU.
      edlvdse EDLVDSE.
      edlvesi EDLVESI.
       eduyrs EDUYRS.
        pdwrk PDWRK.
        edctn EDCTN.
       uempla UEMPLA.
       uempli UEMPLI.
        dsbld DSBLD.
         rtrd RTRD.
        cmsrv CMSRV.
        hswrk HSWRK.
       dngoth DNGOTH.
       dngref DNGREF.
        dngdk DNGDK.
        dngna DNGNA.
      icomdng ICOMDNG.
      mainact MAINACT.
      mnactic MNACTIC.
      icpdwrk ICPDWRK.
       crpdwk CRPDWK.
      pdjobev PDJOBEV.
      pdjobyr PDJOBYR.
      emplrel EMPLREL.
       emplno EMPLNO.
      wrkctra WRKCTRA.
        estsz ESTSZ.
        jbspv JBSPV.
       njbspv NJBSPV.
     wkdcorga WKDCORGA.
      iorgact IORGACT.
        wkhct WKHCT.
       icwhct ICWHCT.
       wkhtot WKHTOT.
       nacer2 NACER2F.
      tporgwk TPORGWK.
       isco08 ISCO08F.
      wrkac6m WRKAC6M.
       uemp3m UEMP3M.
      uemp12m UEMP12M.
      uemp5yr UEMP5YR.
        mbtru MBTRU.
     hincsrca HINCSRCA.
     hinctnta HINCTNTA.
      hincfel HINCFEL.
      icpart3 ICPART3F.
     edulvlpb EDULVLPB.
      eiscedp EISCEDP.
     edlvpeat EDLVPEAT.
     edlvpebe EDLVPEBE.
     edlvpdch EDLVPDCH.
     edlvpdcz EDLVPDCZ.
     edupbde1 EDUPBDE1F.
     edupade2 EDUPADE2F.
     edupade3 EDUPADE3F.
     edlvpdee EDLVPDEE.
     edlvpfes EDLVPFES.
     edlvpdfi EDLVPDFI.
     edlvpdfr EDLVPDFR.
     edupbgb1 EDUPBGB1F.
     edupagb2 EDUPAGB2F.
     edagepgb EDAGEPGB.
     edlvpdhu EDLVPDHU.
     edlvpdie EDLVPDIE.
     edupbil1 EDUPBIL1F.
     edupail2 EDUPAIL2F.
     edlvpdis EDLVPDIS.
     edlvpdit EDLVPDIT.
     edlvpdlt EDLVPDLT.
     edlvpenl EDLVPENL.
     edlvpdno EDLVPDNO.
     edlvpepl EDLVPEPL.
      eduppl2 EDUPPL2F.
     edlvpdpt EDLVPDPT.
     edlvpdru EDLVPDRU.
     edlvpdse EDLVPDSE.
     edlvpesi EDLVPESI.
       pdwrkp PDWRKP.
       edctnp EDCTNP.
      uemplap UEMPLAP.
      uemplip UEMPLIP.
       dsbldp DSBLDP.
        rtrdp RTRDP.
       cmsrvp CMSRVP.
       hswrkp HSWRKP.
      dngothp DNGOTHP.
       dngdkp DNGDKP.
      dngnapp DNGNAPP.
      dngrefp DNGREFP.
       dngnap DNGNAP.
      icomdnp ICOMDNP.
       mnactp MNACTP.
      icppdwk ICPPDWK.
      crpdwkp CRPDWKP.
      isco08p ISCO08P.
      emprelp EMPRELP.
      wkhtotp WKHTOTP.
     edulvlfb EDULVLFB.
      eiscedf EISCEDF.
     edlvfeat EDLVFEAT.
     edlvfebe EDLVFEBE.
     edlvfdch EDLVFDCH.
     edlvfdcz EDLVFDCZ.
     edufbde1 EDUFBDE1F.
     edufade2 EDUFADE2F.
     edufade3 EDUFADE3F.
     edlvfdee EDLVFDEE.
     edlvffes EDLVFFES.
     edlvfdfi EDLVFDFI.
     edlvfdfr EDLVFDFR.
     edufbgb1 EDUFBGB1F.
     edufagb2 EDUFAGB2F.
     edagefgb EDAGEFGB.
     edlvfdhu EDLVFDHU.
     edlvfdie EDLVFDIE.
     edufbil1 EDUFBIL1F.
     edufail2 EDUFAIL2F.
     edlvfdis EDLVFDIS.
     edlvfdit EDLVFDIT.
     edlvfdlt EDLVFDLT.
     edlvfenl EDLVFENL.
     edlvfdno EDLVFDNO.
     edlvfepl EDLVFEPL.
     edlvfdpt EDLVFDPT.
     edlvfdru EDLVFDRU.
     edlvfdse EDLVFDSE.
     edlvfesi EDLVFESI.
      emprf14 EMPRF14F.
      occf14b OCCF14B.
     edulvlmb EDULVLMB.
      eiscedm EISCEDM.
     edlvmeat EDLVMEAT.
     edlvmebe EDLVMEBE.
     edlvmdch EDLVMDCH.
     edlvmdcz EDLVMDCZ.
     edumbde1 EDUMBDE1F.
     edumade2 EDUMADE2F.
     edumade3 EDUMADE3F.
     edlvmdee EDLVMDEE.
     edlvmfes EDLVMFES.
     edlvmdfi EDLVMDFI.
     edlvmdfr EDLVMDFR.
     edumbgb1 EDUMBGB1F.
     edumagb2 EDUMAGB2F.
     edagemgb EDAGEMGB.
     edlvmdhu EDLVMDHU.
     edlvmdie EDLVMDIE.
     edumbil1 EDUMBIL1F.
     edumail2 EDUMAIL2F.
     edlvmdis EDLVMDIS.
     edlvmdit EDLVMDIT.
     edlvmdlt EDLVMDLT.
     edlvmenl EDLVMENL.
     edlvmdno EDLVMDNO.
     edlvmepl EDLVMEPL.
     edlvmdpt EDLVMDPT.
     edlvmdru EDLVMDRU.
     edlvmdse EDLVMDSE.
     edlvmesi EDLVMESI.
      emprm14 EMPRM14F.
      occm14b OCCM14B.
      atncrse ATNCRSE.
      anctry1 ANCTRY1F.
      anctry2 ANCTRY2F.
      ipcrtiv IPCRTIV.
      imprich IMPRICH.
      ipeqopt IPEQOPT.
      ipshabt IPSHABT.
      impsafe IMPSAFE.
      impdiff IMPDIFF.
      ipfrule IPFRULE.
      ipudrst IPUDRST.
      ipmodst IPMODST.
      ipgdtim IPGDTIM.
      impfree IMPFREE.
      iphlppl IPHLPPL.
      ipsuces IPSUCES.
      ipstrgv IPSTRGV.
      ipadvnt IPADVNT.
      ipbhprp IPBHPRP.
      iprspot IPRSPOT.
      iplylfr IPLYLFR.
       impenv IMPENV.
      imptrad IMPTRAD.
       impfun IMPFUN.
       region $REGION.
      regunit REGUNIT.
      intewde INTEWDE.
       inwdds INWDDS.
       inwmms INWMMS.
       inwyys INWYYS.
       inwshh INWSHH.
       inwsmm INWSMM.
       inwdde INWDDE.
       inwmme INWMME.
       inwyye INWYYE.
       inwehh INWEHH.
       inwemm INWEMM.

;
/*To create user-defined missing values .a, .b, .c and .d*/
*%include "C:\ESS\ESS_miss.sas";
run;
